import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("Team Rankings groups assets by position and removes mobile horizontal scrolling", async () => {
  const source = await readFile(new URL("../app/FantasyHub.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  const start = source.indexOf("function TeamRankings(");
  const end = source.indexOf("function PlayerRanks(", start);
  const rankings = source.slice(start, end);
  assert.match(rankings, /team-position-rooms/);
  assert.match(rankings, /\[\.\.\.positions, "OTHER"\]/);
  assert.match(rankings, /team-position-room/);
  assert.match(rankings, /data-position=\{position\}/);
  assert.match(rankings, /role="dialog" aria-modal="true"/);
  assert.match(rankings, /className="team-assets-close"/);
  assert.match(rankings, /createPortal\(drawer, document\.body\)/);
  assert.match(rankings, /className="team-assets-mobile-open"/);
  assert.doesNotMatch(rankings, /team-rank-head/);
  assert.match(rankings, /TOP \{Math\.ceil\(/);
  assert.match(rankings, /% OF LEAGUE/);
  assert.match(rankings, /rank-elite/);
  assert.match(rankings, /rank-trailing/);
  assert.match(rankings, /aria-controls=\{`team-assets-\$\{team\.id\}`\}/);
  assert.match(styles, /\.team-rank-table\{width:100%;overflow-x:hidden!important/);
  assert.match(styles, /\.team-rank-row,.team-rank-row\.dynasty\{position:relative;display:grid;grid-template-columns:repeat\(2,minmax\(0,1fr\)\)!important/);
  assert.match(styles, /\.team-position-room \.team-assets-grid\{grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(styles, /min-width:0!important/);
  assert.match(styles, /\.team-rank-row \.team-rank-toggle\{min-height:44px/);
  assert.match(styles, /\.team-assets-drawer\{position:fixed;z-index:2147483600;inset:max\(54px,calc\(env\(safe-area-inset-top\) \+ 10px\)\)/);
  assert.match(styles, /\.team-assets-mobile-open\{display:block;grid-column:1\/-1/);
  assert.match(styles, /font-family:Impact,"Arial Black",ui-rounded,sans-serif/);
  assert.match(styles, /\.room-rank\.rank-elite b/);
  assert.match(styles, /\.room-rank\.rank-trailing b/);
  assert.doesNotMatch(rankings, /<i>\{expanded \? "−" : "\+"\}<\/i>/);
});
