import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("weekly player rankings are Pro-gated, week-aware, and position limited", async () => {
  const source = await readFile(new URL("../app/FantasyHub.tsx", import.meta.url), "utf8");
  const styles = await readFile(new URL("../app/player-ranks.css", import.meta.url), "utf8");
  const start = source.indexOf("function PlayerRanks(");
  const end = source.indexOf("function AdpPage(", start);
  const rankings = source.slice(start, end);
  const adpEnd = source.indexOf("function WaiverWire(", end);
  const adp = source.slice(end, adpEnd);

  assert.match(rankings, /useState<"season" \| "weekly">\("season"\)/);
  assert.match(rankings, /className="page-content player-rankings-page"/);
  assert.match(rankings, /PRO · WEEK \{Math\.max\(1, week\)\}/);
  assert.match(rankings, /Weekly Player Rankings are a Pro experience/);
  assert.match(rankings, /\{ position: "QB", limit: 24/);
  assert.match(rankings, /\{ position: "RB", limit: 24/);
  assert.match(rankings, /\{ position: "WR", limit: 36/);
  assert.match(rankings, /\{ position: "TE", limit: 24/);
  assert.match(rankings, /projectionScore \* \.45 \+ ceilingScore \* \.25 \+ matchupScore \* \.2 \+ weatherScore \* \.1/);
  assert.match(rankings, /const matchupScore = player\.matchupStrength\?\.score \?\? 50/);
  assert.match(rankings, /<div className="weekly-matchup"><MatchupBadge player=\{player\} \/><\/div>/);
  assert.doesNotMatch(rankings, /<div><span>45%<\/span>/);
  assert.doesNotMatch(rankings, /<div><span>25%<\/span>/);
  assert.doesNotMatch(rankings, /<div><span>20%<\/span>/);
  assert.doesNotMatch(rankings, /<div><span>10%<\/span>/);
  assert.match(rankings, /<span>MATCHUP<\/span><strong>Opponent strength<\/strong>/);
  assert.match(source, /weatherAdjustment: Math\.max\(-\.22, windPenalty \+ rainPenalty \+ coldPenalty\)/);
  assert.match(styles, /\.weekly-matchup > \.matchup-team/);
  assert.match(styles, /\.weekly-position-grid\s*\{[^}]*grid-template-columns: 1fr 1fr/s);
  assert.match(styles, /\.player-rankings-page \.ranking-context span\s*\{[^}]*min-height: 28px;[^}]*padding: 5px 9px;[^}]*font-size: 8px;/s);
  assert.match(styles, /\.player-rankings-page \.ranking-detail-row\s*\{[^}]*grid-template-columns: 34px minmax\(0, 1fr\) 34px 43px 48px;[^}]*min-width: 0;/s);
  assert.match(styles, /\.player-rankings-page \.ranking-detail-row > :nth-child\(n \+ 6\)\s*\{\s*display: none;/s);
  assert.match(styles, /\.player-rankings-page \.ranking-tier-list \.rank-table\s*\{[^}]*overflow-x: hidden;/s);
  assert.match(styles, /@media \(max-width: 980px\)[\s\S]*?\.weekly-position-grid \{ grid-template-columns: 1fr; \}/);
  assert.match(rankings, /\{\["ALL", "QB", "RB", "WR", "TE"\]\.map/);
  assert.doesNotMatch(rankings, /\{\["ALL", "QB", "RB", "WR", "TE", "K", "DEF"\]\.map/);
  assert.match(adp, /\{\["ALL", "QB", "RB", "WR", "TE"\]\.map/);
  assert.doesNotMatch(adp, /\{\["ALL", "QB", "RB", "WR", "TE", "K", "DEF"\]\.map/);
});
