'use client';
import { useEffect, useMemo, useState } from 'react';
import { edgeProjection, edgeSuggestions, isReserve, teamCode, type EdgePlayer, type EdgeContext, type EdgeFeed } from './vegas-edge-model';
import './vegas-edge.css';

export default function VegasEdge({roster,waivers,context,season,week,onPlayer,onWaivers,enabled,onToggle,onFeed}:{roster:EdgePlayer[];waivers:EdgePlayer[];context:EdgeContext;season:string;week:number;onPlayer:(p:EdgePlayer)=>void;onWaivers:()=>void;enabled:boolean;onToggle:(on:boolean)=>void;onFeed:(feed:EdgeFeed)=>void}) {
  const [feed,setFeed]=useState<EdgeFeed|null>(null);
  const [games,setGames]=useState<{date:string;away:{abbreviation:string};home:{abbreviation:string}}[]>([]);
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [refresh,setRefresh]=useState(0);
  const [filter,setFilter]=useState('All');const [clock,setClock]=useState(Date.now);
  useEffect(()=>{if(feed)onFeed(feed);},[feed,onFeed]);
  useEffect(()=>{
    const controller=new AbortController(); let active=true;
    setBusy(true);setError('');
    const json=async(r:Response)=>{const data=await r.json();if(!r.ok)throw new Error(data.error ?? 'Markets unavailable');return data;};
    Promise.all([fetch('/api/vegas-edge',{method:'POST',signal:controller.signal}).then(json),fetch(`/api/nfl-schedule?season=${encodeURIComponent(season)}`,{signal:controller.signal}).then(json)]).then(([data,schedule])=>{if(active){setFeed(data);setGames(schedule.weeks?.find((w:{week:number})=>w.week===week)?.games ?? []);}}).catch(e=>{if(active&&e.name!=='AbortError')setError(e.message);}).finally(()=>{if(active)setBusy(false);});
    return()=>{active=false;controller.abort();};
  },[refresh,season,week]);
  useEffect(()=>{
    // Light visibility-aware clock invalidates stale/locked advice. No animation loop.
    const timer=window.setInterval(()=>{if(document.visibilityState==='visible')setClock(Date.now());},30000);
    const resume=()=>{if(document.visibilityState==='visible')setClock(Date.now());};
    document.addEventListener('visibilitychange',resume);
    return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',resume);};
  },[]);
  const events=useMemo(()=>(feed?.events ?? []).filter(e=>games.some(g=>teamCode(g.away.abbreviation)===e.away&&teamCode(g.home.abbreviation)===e.home&&Math.abs(Date.parse(g.date)-Date.parse(e.startsAt))<12*3600000)),[feed,games]);
  const rows=useMemo(()=>roster.map(p=>edgeProjection(p,events,context,clock)),[roster,events,context,clock]);
  const waiverRows=useMemo(()=>waivers.filter(p=>!roster.some(r=>r.id===p.id)).map(p=>edgeProjection(p,events,context,clock)),[waivers,roster,events,context,clock]);
  const {swaps,targets}=useMemo(()=>edgeSuggestions(rows,waiverRows),[rows,waiverRows]);
  const covered=rows.filter(r=>r.usable).length;
  const starters=rows.filter(r=>!isReserve(r.player.role));
  const coveredStarters=starters.filter(r=>r.usable);
  const delta=coveredStarters.reduce((sum,r)=>sum+(r.delta ?? 0),0);
  const visible=rows.filter(r=>filter==='All'||filter==='Starters'&&!isReserve(r.player.role)||filter==='Bench'&&isReserve(r.player.role)||filter==='Covered'&&r.usable);
  const signed=(n:number)=>`${n>0?'+':''}${n.toFixed(1)}`;
  const timestamp=(date:string)=>new Date(date).toLocaleString(undefined,{weekday:'short',hour:'numeric',minute:'2-digit'});
  return <div className="page-content vegas-edge-page">
    <section className="panel edge-intro"><div><span className="edge-eyebrow">ELITE · OWNER PREVIEW</span><h2>Vegas Edge</h2><p>Market insight. Smarter lineup decisions.</p></div><button type="button" className="edge-refresh" disabled={busy} onClick={()=>setRefresh(n=>n+1)}>{busy?'Checking markets…':'Check markets'}</button></section>
    <section className="panel edge-source-toggle"><div><h3>Use Vegas projections across the Hub</h3><p>Switch weekly projections, matchup outlooks and lineup tools to Vegas Implied Projections. Live and final scores stay unchanged.</p><small>Missing or stale markets keep their platform projection. Vegas estimates use the market blend explained below. This preference applies on this device.</small></div><button type="button" role="switch" aria-checked={enabled} aria-label="Use Vegas Implied Projections across the app" onClick={()=>onToggle(!enabled)}><span aria-hidden="true"/>{enabled?'On':'Off'}</button></section>
    {error && <p className="panel" role="alert">{error} <button onClick={()=>setRefresh(n=>n+1)}>Try again</button></p>}
    <section className="panel edge-connection" role="status"><b>{!feed?'Connecting…':feed.configured?'SportsGameOdds':'Awaiting API connection'}</b><span>{feed?.message ?? 'Checking your market connection.'}</span>{feed?.checkedAt&&<small>Last check {timestamp(feed.checkedAt)} · {feed.usage ?? '—'} / {feed.budget} object safety budget</small>}</section>
    <div className="edge-metrics"><section className="panel"><small>ROSTER COVERAGE</small><strong>{covered}<em> / {rows.length}</em></strong><span>Players with usable projections</span></section><section className="panel"><small>COVERED STARTER EDGE</small><strong>{coveredStarters.length?signed(delta):'—'}</strong><span>{coveredStarters.length} of {starters.length} starters · not a full-team total</span></section><section className="panel"><small>LINEUP OPPORTUNITIES</small><strong>{swaps.length}</strong><span>Eligible, unlocked bench swaps</span></section></div>
    <section className="panel edge-board"><header><div><h3>Your roster, through the market</h3><p>Week {week} · {context.scoring} · Your league’s scoring · Pregame estimates</p></div><div className="edge-filters" aria-label="Roster filters">{['All','Starters','Bench','Covered'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div></header>
      <div className="edge-table-wrap"><table><thead><tr><th>Player</th><th>Baseline</th><th>Vegas blend</th><th>Edge</th></tr></thead><tbody>{visible.map(r=><tr key={r.player.id}><td><button className="edge-player" onClick={()=>onPlayer(r.player)}>{r.player.name}</button><small>{r.player.position} · {r.player.team} · {r.player.role}</small><span className={`edge-status ${r.usable?'is-covered':''}`}>{r.label}{r.questionable?' · Questionable':''}</span>{r.props.length>0&&<details><summary>{r.props.length} prop markets</summary><ul>{r.props.map(p=><li key={p.stat}>{p.stat.replaceAll('_',' ')} <b>{p.line}</b> <small>{p.source==='provider-fair'?'Fair consensus':`${p.books} books`}</small></li>)}</ul>{r.event&&<small>Snapshot {timestamp(r.event.updatedAt)} · Kickoff {timestamp(r.event.startsAt)}</small>}</details>}</td><td>{r.baseline.toFixed(1)}</td><td className="edge-projection">{r.projection?.toFixed(1) ?? '—'}</td><td data-direction={(r.delta ?? 0)>0?'up':(r.delta ?? 0)<0?'down':'flat'}>{r.delta===null?'—':signed(r.delta)}</td></tr>)}</tbody></table></div>
      {!visible.length&&<p className="edge-empty">No players match this filter yet.</p>}
    </section>
    <div className="edge-actions-grid"><section className="panel"><h3>Lineup opportunities</h3><p>Individual alternatives—not automatic lineup changes.</p>{swaps.length?swaps.map(s=><article className="edge-opportunity" key={s.into.player.id}><span className="edge-gain">+{s.gain.toFixed(1)} pts</span><b>Start <button onClick={()=>onPlayer(s.into.player)}>{s.into.player.name}</button></b><span>Over {s.out.player.name} at {s.out.player.role}</span></article>):<p className="edge-empty">{covered?'No clear, eligible upgrades from the covered players.':'Suggestions appear when both players have fresh, usable props.'}</p>}</section><section className="panel"><h3>Waiver watch</h3><p>Available players who could improve an eligible starter slot.</p>{targets.length?targets.map(s=><article className="edge-opportunity" key={s.into.player.id}><span className="edge-gain">+{s.gain.toFixed(1)} pts</span><button className="edge-player" onClick={()=>onPlayer(s.into.player)}>{s.into.player.name}</button><span>{s.into.player.position} · Alternative to {s.out.player.name}</span><small>Check roster space and waiver availability before adding.</small></article>):<p className="edge-empty">No supported waiver upgrades yet. Partial props won’t trigger recommendations.</p>}<button className="edge-link" onClick={onWaivers}>Review Waiver Wire →</button></section></div>
    <section className="panel"><h3>Game environment</h3><div className="edge-games">{events.map(e=><article key={e.id}><b>{e.away} at {e.home}</b><small>{timestamp(e.startsAt)} · {e.locked||Date.parse(e.startsAt)<=clock?'Locked':'Pregame'}</small><span>Total <strong>{e.total ?? '—'}</strong> · {e.home} spread <strong>{e.homeSpread===null?'—':e.homeSpread>0?`+${e.homeSpread}`:e.homeSpread}</strong></span></article>)}</div>{!events.length&&<p className="edge-empty">Game totals and spreads will appear after the market connection is active.</p>}</section>
    <details className="panel edge-method"><summary>Understand your edge</summary><p>Vegas blend combines 60% prop-derived scoring with 40% of your existing projection. It is an experimental market-informed estimate, not a sportsbook’s fantasy-point projection. Prop lines are not statistical means.</p><p>Available main over/under markets use paired book prices. Anytime touchdowns can also use the provider’s fair Yes/No consensus when books offer only one side. The displayed line is the median across qualifying books. TD and interception counts use a Poisson approximation informed by the odds, rather than treating the line as an expected average. Bonuses, fumbles, and secondary stats are not fully modeled; the baseline blend does not guarantee their exact contribution.</p><p>Incomplete coverage, unknown league scoring, stale lines, unavailable players, and games that have started do not produce recommendations. Questionable players need a status check and are excluded from suggested moves. These are separate alternatives, not cumulative guaranteed gains.</p><p>Refresh checks are shared and rate-limited: every 12 hours early in the week, every 2 hours in the final day, and every 10 minutes in the final 2 hours. During owner preview, checks run when you open this page or choose Check markets. Unattended scheduling will be connected after API verification.</p></details>
  </div>;
}
